// =============================================
// UI - CACHE DE ELEMENTOS DOM
// Mapa de referencias a elementos DOM usados na renderizacao de campos.
// =============================================

export const ids = {
  CharClass:   document.getElementById('CharClass'),
  CharLvl:     document.getElementById('CharLvl'),
  CharArcana:  document.getElementById('CharArcana'),
  CharPlayer:  document.getElementById('CharPlayer'),
  CharSTR:     document.getElementById('CharSTR'),
  CharMAG:     document.getElementById('CharMAG'),
  CharTEC:     document.getElementById('CharTEC'),
  CharAGI:     document.getElementById('CharAGI'),
  CharVIT:     document.getElementById('CharVIT'),
  CharLCK:     document.getElementById('CharLCK'),
  MaxHP:       document.getElementById('MaxHP'),
  CurrentHP:   document.getElementById('CurrentHP'),
  EnergyMax:   document.getElementById('EnergyMax'),
  CurrentPM:   document.getElementById('CurrentPM'),
  DmgRed:      document.getElementById('DmgRed'),
  KNOPts:      document.getElementById('KNOPts'),
  DISPts:      document.getElementById('DISPts'),
  EMPpts:      document.getElementById('EMPpts'),
  EXPPts:      document.getElementById('EXPPts'),
  COUPts:      document.getElementById('COUPts'),
  CHAPts:      document.getElementById('CHAPts'),
  Aspectos:    document.getElementById('Aspectos'),
  AspectPoints:document.getElementById('AspectPoints'),
  Buffs:       document.getElementById('Buffs'),
  PerName:     document.getElementById('PerName'),
  PerArcana:   document.getElementById('PerArcana'),
  PerNotes:    document.getElementById('PerNotes'),
  Conviction:  document.getElementById('Conviction'),
  PerLvl:      document.getElementById('PerLvl'),
  PerSP:       document.getElementById('PerSP'),
  PerTypes:    document.getElementById('PerTypes'),
  Weapon:      document.getElementById('Weapon'),
  WeaponDmg:   document.getElementById('WeaponDmg'),
  WeaponReach: document.getElementById('WeaponReach'),
  WeaponEffect:document.getElementById('WeaponEffect'),
  Armor:       document.getElementById('Armor'),
  ArmorDmgRed: document.getElementById('ArmorDmgRed'),
  ArmorEffect: document.getElementById('ArmorEffect'),
  Accessory:   document.getElementById('Accessory'),
  AccessoryEffect: document.getElementById('AccessoryEffect'),
  Resistances: document.getElementById('Resistances'),
  NotesDiary:  document.getElementById('NotesDiary'),
  NotesGoals:  document.getElementById('NotesGoals')
};
